
services:
  appwrite:
    image: appwrite/appwrite:latest
    container_name: appwrite
    environment:
      - _APP_ENV=development
      - _APP_OPENSSL_KEY_V1=your-secret-key
      - _APP_DOMAIN=localhost
      - _APP_PLATFORM=web
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./appwrite:/storage:rw
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:80"  # Serve the React app on port 3001
    volumes:
      - ./frontend:/app
    command: npm run dev  # Start React frontend in development mode
